run:
  concurrency: 4
  timeout: 1m
  issues-exit-code: 1
  tests: true

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - goimports
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - asciicheck
    - bodyclose
    - cyclop
    - gofmt
    - dupl
    - durationcheck
    - errname
    - exhaustive
    - forcetypeassert
    - gocritic
    - revive
    - unconvert
    - gosec

linters-settings:
  goimports:
    local-prefixes: github.com/tender-barbarian/
  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: if-return
      - name: superfluous-else
      - name: get-return
      - name: modifies-parameter
      - name: unused-parameter
      - name: unreachable-code

